# Generated by Django 3.2.8 on 2021-10-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=200)),
                ('monthly_salary', models.CharField(max_length=200)),
                ('hiring_process', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=200)),
                ('company_website', models.URLField()),
                ('about_company', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
