# Generated by Django 3.2.8 on 2021-10-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
