# Generated by Django 3.2.8 on 2021-10-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjs_app', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='job_type',
            field=models.CharField(choices=[('FULL TIME', 'Full Time'), ('PART TIME', 'Part Time'), ('INTERNSHIP', 'Internship')], max_length=20),
        ),
    ]
