# Generated by Django 3.2.8 on 2021-10-14 04:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjs_app', '0004_auto_20211013_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
