# Generated by Django 3.2.8 on 2021-10-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gjs_app', '0008_alter_post_work_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='last_date',
        ),
    ]
