# Generated by Django 3.2.8 on 2021-10-16 02:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gjs_app', '0009_rename_date_post_last_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='work_from',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('WORK FROM HOME', 'Work From Home')], max_length=14, null=True),
        ),
    ]
